name: Build & Test

on: [push, pull_request]

env:
  KONG_SOURCE_LOCATION: $$GITHUB_WORKSPACE
  KONG_BUILD_TOOLS_LOCATION: $HOME/kong-build-tools

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
    - name: Set env
      run: |
          echo "::set-env name=KONG_SOURCE_LOCATION::$GITHUB_WORKSPACE"
          echo "::set-env name=KONG_BUILD_TOOLS_LOCATION::$HOME/kong-build-tools"
        
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Setup Kong Build Tools
      run: make setup-kong-build-tools

    - name: Build Test Image
      run: pushd $KONG_BUILD_TOOLS_LOCATION && make kong-test-container && popd

  integration-tests-dbless:
    name: DB-less tests
    runs-on: ubuntu-18.04
    needs: build

    env:
      KONG_TEST_DATABASE: 'off'
      TEST_SUITE: dbless
      
    steps:
    - name: Set env
      run: |
          echo "::set-env name=KONG_SOURCE_LOCATION::$GITHUB_WORKSPACE"
          echo "::set-env name=KONG_BUILD_TOOLS_LOCATION::$HOME/kong-build-tools"
        
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Setup Kong Build Tools
      run: make setup-kong-build-tools

    - name: Run Tests
      run: pushd $KONG_BUILD_TOOLS_LOCATION && make test-kong && popd

  integration-tests-with-databases:
    name: ${{matrix.database}} (${{ matrix.suite }}) integration tests
    runs-on: ubuntu-18.04
    needs: build

    strategy:
      matrix:
        suite: [integration, plugins]
        database: [cassandra, postgres]

    env:
      KONG_TEST_DATABASE: ${{ matrix.database }}
      TEST_SUITE: ${{ matrix.suite }}

    steps:
    - name: Set env
      run: |
          echo "::set-env name=KONG_SOURCE_LOCATION::$GITHUB_WORKSPACE"
          echo "::set-env name=KONG_BUILD_TOOLS_LOCATION::$HOME/kong-build-tools"
        
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Setup Kong Build Tools
      run: make setup-kong-build-tools

    - name: Run Tests
      run: pushd $KONG_BUILD_TOOLS_LOCATION && make test-kong && popd

  tests-without-a-database:
    name: Tests without a datastore
    runs-on: ubuntu-18.04
    needs: build

    strategy:
      matrix:
        suite: [unit, pdk]

    env:
      TEST_SUITE: ${{ matrix.suite }}

    steps:
    - name: Set env
      run: |
          echo "::set-env name=KONG_SOURCE_LOCATION::$GITHUB_WORKSPACE"
          echo "::set-env name=KONG_BUILD_TOOLS_LOCATION::$HOME/kong-build-tools"
        
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Setup Kong Build Tools
      run: make setup-kong-build-tools

    - name: Run Tests
      run: pushd $KONG_BUILD_TOOLS_LOCATION && make test-kong && popd
